In [1]:
import tensorflow as tf

In [2]:
# y=mx+c

In [4]:
m=tf.constant(3.0,name='m')
c=tf.constant(1.5,name='c')
x=tf.placeholder(dtype='float32',name='x')

In [9]:
y=m*x+c

In [10]:
sess=tf.Session()

In [12]:
y.eval({x:3},session=sess)

10.5

In [13]:
#2-d 
M=tf.constant([[1,2],[3,5]],dtype='float32')

In [14]:
#1-d
v=tf.constant([5,23],dtype='float32')

In [15]:
sess1=tf.Session()

In [16]:
sess1.run(M+v)

array([[ 6., 25.],
       [ 8., 28.]], dtype=float32)

In [17]:
sess1.run(M*v)

array([[  5.,  46.],
       [ 15., 115.]], dtype=float32)

In [18]:
M.dtype

tf.float32

In [19]:
M.shape

TensorShape([Dimension(2), Dimension(2)])

In [20]:
v.shape

TensorShape([Dimension(2)])

In [22]:
sess1.run(tf.matmul(M,tf.reshape(v,[2,1])))

array([[ 51.],
       [130.]], dtype=float32)

In [25]:
x=tf.constant([1,3.])
y=tf.constant(5.)

In [26]:
sess1.run(x+y)

array([6., 8.], dtype=float32)

In [30]:
x.shape,y.shape

(TensorShape([Dimension(2)]), TensorShape([]))